config/routes.rb
Rails.application.routes.draw do
  resources :diver_reviews
  resources :location_reviews
  resources :locations
  resources :location_lists
  resources :profiles
  resources :chat_rooms, only: [:new, :create, :show, :index]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #  routes for private chat
  resources :conversations do
    resources :messenger
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'locations#index'
  # root 'profiles#current_user_show'
end

app/controllers/location_reviews_controller.rb
class LocationReviewsController < ApplicationController
  before_action :set_location_review, only: [:show, :edit, :update, :destroy]
  before_action :set_location, only: [:new]

  # GET /location_reviews
  # GET /location_reviews.json
  def index
    @location_reviews = LocationReview.all
  end

  # GET /location_reviews/1
  # GET /location_reviews/1.json
  def show
  end

  # GET /location_reviews/new
  def new
    @location_review = LocationReview.new
  end

  # GET /location_reviews/1/edit
  def edit
  end

  # POST /location_reviews
  # POST /location_reviews.json
  def create
    @location_review = LocationReview.new(location_review_params)
    @location_review.profile_id = current_user.profile.id
    respond_to do |format|
      if @location_review.save
        format.html { redirect_to @location_review, notice: 'Location review was successfully created.' }
        format.json { render :show, status: :created, location: @location_review }
      else
        format.html { render :new }
        format.json { render json: @location_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /location_reviews/1
  # PATCH/PUT /location_reviews/1.json
  def update
    respond_to do |format|
      if @location_review.update(location_review_params)
        format.html { redirect_to @location_review, notice: 'Location review was successfully updated.' }
        format.json { render :show, status: :ok, location: @location_review }
      else
        format.html { render :edit }
        format.json { render json: @location_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_reviews/1
  # DELETE /location_reviews/1.json
  def destroy
    @location_review.destroy
    respond_to do |format|
      format.html { redirect_to location_reviews_url, notice: 'Location review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location_review
      @location_review = LocationReview.find(params[:id])
    end

    def set_location
      @location_id = params[:location]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_review_params
      params.require(:location_review).permit(:profile_id, :location_id, :review, :rating)
    end
end

app/helpers/location_reviews_helper.rb
module LocationReviewsHelper
end

app/views/location_reviews/_form.html.erb
<%= form_for(location_review) do |f| %>
  <% if location_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location_review.errors.count, "error") %> prohibited this location_review from being saved:</h2>

      <ul>
      <% location_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.hidden_field :location_id, :value => @location_id %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_area :review %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/location_reviews/edit.html.erb
<h1>Editing Location Review</h1>

<%= render 'form', location_review: @location_review %>

<%= link_to 'Show', @location_review %> |
<%= link_to 'Back', location_reviews_path %>

app/views/location_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Location Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Location</th>
      <th>Review</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @location_reviews.each do |location_review| %>
      <tr>
        <td><%= location_review.profile.name %></td>
        <td><%= location_review.location.location_name %></td>
        <td><%= location_review.review %></td>
        <td><%= location_review.rating %></td>
        <td><%= link_to 'Show', location_review %></td>
        <td><%= link_to 'Edit', edit_location_review_path(location_review) %></td>
        <td><%= link_to 'Destroy', location_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location Review', new_location_review_path %>

app/views/location_reviews/new.html.erb
<h1>New Location Review</h1>

<%= render 'form', location_review: @location_review %>

<%= link_to 'Back', location_reviews_path %>

app/views/location_reviews/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Profile:</strong>
  <%= @location_review.profile.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @location_review.location.location_name %>
</p>

<p>
  <strong>Review:</strong>
  <%= @location_review.review %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @location_review.rating %>
</p>

<%= link_to 'Back to location', locations_path %>
<%= link_to 'Home', root_path %>