config/routes.rb
Rails.application.routes.draw do
  resources :diver_reviews
  resources :location_reviews
  resources :locations
  resources :location_lists
  resources :profiles
  resources :chat_rooms, only: [:new, :create, :show, :index]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #  routes for private chat
  resources :conversations do
    resources :messenger
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'locations#index'
  # root 'profiles#current_user_show'
end

app/controllers/diver_reviews_controller.rb
class DiverReviewsController < ApplicationController
  before_action :set_diver_review, only: [:show, :edit, :update, :destroy]

  # GET /diver_reviews
  # GET /diver_reviews.json
  def index
    @diver_reviews = DiverReview.all
  end

  # GET /diver_reviews/1
  # GET /diver_reviews/1.json
  def show
  end

  # GET /diver_reviews/new
  def new
    @diver_review = DiverReview.new
  end

  # GET /diver_reviews/1/edit
  def edit
  end

  # POST /diver_reviews
  # POST /diver_reviews.json
  def create
    @diver_review = DiverReview.new(diver_review_params)

    respond_to do |format|
      if @diver_review.save
        format.html { redirect_to @diver_review, notice: 'Diver review was successfully created.' }
        format.json { render :show, status: :created, location: @diver_review }
      else
        format.html { render :new }
        format.json { render json: @diver_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diver_reviews/1
  # PATCH/PUT /diver_reviews/1.json
  def update
    respond_to do |format|
      if @diver_review.update(diver_review_params)
        format.html { redirect_to @diver_review, notice: 'Diver review was successfully updated.' }
        format.json { render :show, status: :ok, location: @diver_review }
      else
        format.html { render :edit }
        format.json { render json: @diver_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diver_reviews/1
  # DELETE /diver_reviews/1.json
  def destroy
    @diver_review.destroy
    respond_to do |format|
      format.html { redirect_to diver_reviews_url, notice: 'Diver review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diver_review
      @diver_review = DiverReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diver_review_params
      params.require(:diver_review).permit(:profile_id, :diver_review, :diver_rating)
    end
end

app/helpers/diver_reviews_helper.rb
module DiverReviewsHelper
end

app/views/diver_reviews/_form.html.erb
<%= form_for(diver_review) do |f| %>
  <% if diver_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diver_review.errors.count, "error") %> prohibited this diver_review from being saved:</h2>

      <ul>
      <% diver_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %>
    <%= f.text_field :profile_id %>
  </div>

  <div class="field">
    <%= f.label :diver_review %>
    <%= f.text_area :diver_review %>
  </div>

  <div class="field">
    <%= f.label :diver_rating %>
    <%= f.number_field :diver_rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diver_reviews/edit.html.erb
<h1>Editing Diver Review</h1>

<%= render 'form', diver_review: @diver_review %>

<%= link_to 'Show', @diver_review %> |
<%= link_to 'Back', diver_reviews_path %>

app/views/diver_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diver Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Diver review</th>
      <th>Diver rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diver_reviews.each do |diver_review| %>
      <tr>
        <td><%= diver_review.profile %></td>
        <td><%= diver_review.diver_review %></td>
        <td><%= diver_review.diver_rating %></td>
        <td><%= link_to 'Show', diver_review %></td>
        <td><%= link_to 'Edit', edit_diver_review_path(diver_review) %></td>
        <td><%= link_to 'Destroy', diver_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diver Review', new_diver_review_path %>

app/views/diver_reviews/new.html.erb
<h1>New Diver Review</h1>

<%= render 'form', diver_review: @diver_review %>

<%= link_to 'Back', diver_reviews_path %>

app/views/diver_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @diver_review.profile %>
</p>

<p>
  <strong>Diver review:</strong>
  <%= @diver_review.diver_review %>
</p>

<p>
  <strong>Diver rating:</strong>
  <%= @diver_review.diver_rating %>
</p>

<%= link_to 'Edit', edit_diver_review_path(@diver_review) %> |
<%= link_to 'Back', diver_reviews_path %>