config/routes.rb
Rails.application.routes.draw do
  resources :diver_reviews
  resources :location_reviews
  resources :locations
  resources :location_lists
  resources :profiles
  resources :chat_rooms, only: [:new, :create, :show, :index]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #  routes for private chat
  resources :conversations do
    resources :messenger
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'locations#index'
  # root 'profiles#current_user_show'
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :location_lists
  has_many :profiles, through: :location_lists
  has_many :location_reviews, dependent: :destroy

  # after_create :create_location_list

  reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # Cacncancan not authorised redirect to root
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  # GET /locations
  # GET /locations.json
  def index
    if !user_signed_in?
      redirect_to new_user_registration_path
    elsif current_user.profile.nil?
      @profile = Profile.new
      redirect_to new_profile_path
    else
      @locations = Location.all
    end

  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @nearbys = Location.near([@location.latitude, @location.longitude], 20, :units => :km)
    @location_list = LocationList.new
    @locations = Location.all
    @location_reviews = @location.location_reviews
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:location_name, :description, :depth, :difficulty, :latitude, :longitude, :location_lists_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_name %>
    <%= f.text_field :location_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :depth %>
    <%= f.text_field :depth %>
  </div>

  <div class="field">
    <%= f.label :difficulty %>
    <%= f.text_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Location name</th>
      <th>Description</th>
      <th>Depth</th>
      <th>Difficulty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.location_name, location %></td>
        <td><%= location.description %></td>
        <td><%= location.depth %></td>
        <td><%= location.difficulty %></td>
        <td>
          <% if can? :update, @location %>
          <%= link_to "Edit", edit_location_path(location.id) %>
          <% end %>
        </td>
        <td>
          <% if can? :update, @location %>
          <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>
<%= link_to 'View Profile', current_user.profile %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
  <p id="notice"><%= notice %></p>

<div class="maprow row">
    <div class="col-md-6 mapdiv">
      <div id="map"></div>

    </div>

  <div class="col-md-6 detailsdiv">
    <p>
      <strong>Location name:</strong>
      <%= @location.location_name %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @location.description %>
    </p>
    <p>
      <strong>Depth:</strong>
      <%= @location.depth %>
    </p>
    <p>
      <strong>Difficulty:</strong>
      <%= @location.difficulty %>
    </p>
    <p>
      <strong>Latitude:</strong>
      <%= @location.latitude %>
    </p>
    <p>
      <strong>Longitude:</strong>
      <%= @location.longitude %>
    </p>
  </div>
</div>

<%= render 'location_lists/form', location_list: @location_list, location: @location %>
<%= link_to 'Back to Locations', locations_path %>

<h1 class="header">Users who also want to dive here</h1>

<ul>
  <% @location.profiles.each do |profile| %>
    <li>
      <%= link_to profile.name, profile_url(profile.id) %>
    </li>
  <% end %>
</ul>
 
<%= link_to 'Add Review', new_location_review_path(location: @location.id) %>
<br>
<%= "Location reviews" %>
<ul>
  <% @location_reviews.each do |review| %>
    <li>
      <%= review.review %>
      <%= review.rating %>
    </li>
    <% end %>
</ul>

<script>
  function initMap() {
    var myLatLng = {lat: <%= @location.latitude %>, lng: <%= @location.longitude %>};
    //display map on page centred over chosen destination
    var map = new google.maps.Map(document.getElementById('map'), {
      center: myLatLng,
      zoom: 11
    });
    // Loop through locations index and place marker on map
    <% @nearbys.each_with_index do |nearby, i| %>
      var marker<%=i%> = new google.maps.Marker({
        position: { lat: <%= nearby.latitude %>, lng: <%= nearby.longitude %> },
        map: map,
        title: '<%= nearby.location_name %>'
      });
      // Adds content to info box for each location
      var contentString = '<div id="content">'+
          '<div id="siteNotice">'+
          '</div>'+
          '<h1 id="firstHeading" class="firstHeading"><%= link_to nearby.location_name, location_path(nearby) %></h1>'+
          '<div id="bodyContent">'+
          '<p><%= "Description: " %><%= nearby.description %><br>'+
          '<%= "Depth: " %><%= nearby.depth %><br>'+
          '<%= "Difficulty: " %><%= nearby.difficulty %><br>'+
          '<%= "Latitude: " %><%= nearby.latitude %><br>'+
          '<%= "Longitude: " %><%= nearby.longitude %></p>'+
          '</div>'+
          '</div>';
      // Sets infowindow variable to be used below
      var infowindow<%=i%> = new google.maps.InfoWindow({
      content: contentString
      });
      // Attaches info window to marker
      marker<%=i%>.addListener('click', function() {
      infowindow<%=i%>.open(map, marker<%=i%>);
      });
    <% end %>
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvTY_nvQt--eg9ArutXjvr8qq1iWaWnWY&callback=initMap"
async defer></script>